### PR TITLE
Add cache type

### PR DESCRIPTION
**Pull request by ton-katsu**
Thank you for your great works. I added cache type for image animation.

### CODE REVIEW

**Comment by hirohisa** [comment]
Thanks you for your pull-request, @ton-katsu .
Is `Cache Type` a handler for downloading image to save in `ImageCache` or not ?
Or Where image is loaded from?

**Comment by ton-katsu** [comment]
I want to check Where image is loaded from.

* If image is loaded from the internet(no cache), start fade in animation.
* If image is loaded from the disk, display immediately.

```
UIImageView.load(url, placeholder: nil) { _, _, _, cacheType in
    if cacheType == CacheType.None {
        UIView.animateWithDuration(0.5, animations: {
            UIImageView.alpha = 0
            UIImageView.alpha = 1
        })
    }
}
```

Do you have any solutions?

**Comment by hirohisa** [comment]
Thanks! Seems good about where image is loaded from.
I will rename `CacheType.Disk` to `CacheType.Cache`, because `ImageCache` can be customized for `MemoryCache`.

**Comment by ton-katsu** [comment]
Thank you very much!

**Pull request merged**
